### ISSUE TITLE
crashes when added to config.json

### ISSUE THREAD

**Issue by daaf84** [StefanNienhuis/homebridge-triggi#2]
first had Triggi add-on, all worked. Bur nog I changed to Ostilo. Cant get it to work anymore with my trigs... first installed via webconfig (NPM), but had error. So installed from the command line. No errors, but when I add the settings to the config.json, it crashes

**Comment by daaf84** [comment]
"platforms": [
{
      "platform": "config",
      "name": "Config",
      "port": 8080,
      "sudo": false
    },
        {
        "platform": "Olisto",
        "triggs": [
            {
                "name": "KaKu",
                "type": "switch",
                "connecturl": "https://connect.triggi.com/c/xxx"
            },

	    {
                "name": "KaKu WCD",
                "type": "switch",
                "connecturl": "https://connect.triggi.com/c/xxx"
            }
         ]
         }
    ]
}

**Comment by StefanNienhuis** [comment]
Could you please post the error that my plugin gives?

**Comment by daaf84** [comment]
This is from the command line:

`
pi@homebridge:~ $ systemctl status homebridge
● homebridge.service - Node.js HomeKit Server
   Loaded: loaded (/etc/systemd/system/homebridge.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2018-02-14 14:17:15 CET; 55s ago
 Main PID: 251 (homebridge)
   CGroup: /system.slice/homebridge.service
           └─251 homebridge

Feb 14 14:17:22 homebridge node[251]: *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSSer
Feb 14 14:18:00 homebridge homebridge[251]: [2/14/2018, 2:18:00 PM] Loaded plugin: homebridge-config-ui-x
Feb 14 14:18:00 homebridge homebridge[251]: [2/14/2018, 2:18:00 PM] Registering platform 'homebridge-config-ui-x.config'
Feb 14 14:18:00 homebridge homebridge[251]: [2/14/2018, 2:18:00 PM] ---
Feb 14 14:18:01 homebridge homebridge[251]: [2/14/2018, 2:18:01 PM] Loaded plugin: homebridge-hyperion-light
Feb 14 14:18:01 homebridge homebridge[251]: [2/14/2018, 2:18:01 PM] Registering accessory 'homebridge-hyperion.Hyperion'
Feb 14 14:18:01 homebridge homebridge[251]: [2/14/2018, 2:18:01 PM] ---
Feb 14 14:18:10 homebridge homebridge[251]: [2/14/2018, 2:18:10 PM] Loaded plugin: homebridge-nefit-easy
Feb 14 14:18:10 homebridge homebridge[251]: [2/14/2018, 2:18:10 PM] Registering accessory 'homebridge-nefit-easy.NefitEasy'
Feb 14 14:18:10 homebridge homebridge[251]: [2/14/2018, 2:18:10 PM] ---
pi@homebridge:~ $ systemctl status homebridge
● homebridge.service - Node.js HomeKit Server
   Loaded: loaded (/etc/systemd/system/homebridge.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Wed 2018-02-14 14:18:15 CET; 2s ago
  Process: 251 ExecStart=/usr/local/bin/homebridge $HOMEBRIDGE_OPTS (code=exited, status=1/FAILURE)
 Main PID: 251 (code=exited, status=1/FAILURE)

Feb 14 14:18:15 homebridge systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE
Feb 14 14:18:15 homebridge systemd[1]: homebridge.service: Unit entered failed state.
Feb 14 14:18:15 homebridge systemd[1]: homebridge.service: Failed with result 'exit-code'.
`

**Comment by daaf84** [comment]
When I don't define olisto in the config, it runs normal:

Feb 14 14:18:54 homebridge systemd[1]: Started Node.js HomeKit Server.
Feb 14 14:18:57 homebridge homebridge[479]: *** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
Feb 14 14:18:57 homebridge homebridge[479]: *** WARNING *** Please fix your application to use the native API of Avahi!
Feb 14 14:18:57 homebridge homebridge[479]: *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
Feb 14 14:18:57 homebridge homebridge[479]: *** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
Feb 14 14:18:57 homebridge homebridge[479]: *** WARNING *** Please fix your application to use the native API of Avahi!
Feb 14 14:18:57 homebridge homebridge[479]: *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
Feb 14 14:19:17 homebridge homebridge[479]: [2/14/2018, 2:19:17 PM] Loaded plugin: homebridge-config-ui-x
Feb 14 14:19:17 homebridge homebridge[479]: [2/14/2018, 2:19:17 PM] Registering platform 'homebridge-config-ui-x.config'
Feb 14 14:19:17 homebridge homebridge[479]: [2/14/2018, 2:19:17 PM] ---
Feb 14 14:19:19 homebridge homebridge[479]: [2/14/2018, 2:19:19 PM] Loaded plugin: homebridge-hyperion-light
Feb 14 14:19:19 homebridge homebridge[479]: [2/14/2018, 2:19:19 PM] Registering accessory 'homebridge-hyperion.Hyperion'
Feb 14 14:19:19 homebridge homebridge[479]: [2/14/2018, 2:19:19 PM] ---
Feb 14 14:19:26 homebridge homebridge[479]: [2/14/2018, 2:19:26 PM] Loaded plugin: homebridge-nefit-easy
Feb 14 14:19:26 homebridge homebridge[479]: [2/14/2018, 2:19:26 PM] Registering accessory 'homebridge-nefit-easy.NefitEasy'
Feb 14 14:19:26 homebridge homebridge[479]: [2/14/2018, 2:19:26 PM] ---
Feb 14 14:19:30 homebridge homebridge[479]: [2/14/2018, 2:19:30 PM] Loaded plugin: homebridge-olisto
Feb 14 14:19:30 homebridge homebridge[479]: [2/14/2018, 2:19:30 PM] Registering platform 'homebridge-olisto.Olisto'
Feb 14 14:19:30 homebridge homebridge[479]: [2/14/2018, 2:19:30 PM] Registering accessory 'homebridge-olisto.OlistoAccessory'
Feb 14 14:19:30 homebridge homebridge[479]: [2/14/2018, 2:19:30 PM] ---
Feb 14 14:19:30 homebridge homebridge[479]: [2/14/2018, 2:19:30 PM] Loaded config.json with 2 accessories and 1 platforms.
Feb 14 14:19:30 homebridge homebridge[479]: [2/14/2018, 2:19:30 PM] ---
Feb 14 14:19:30 homebridge homebridge[479]: [2/14/2018, 2:19:30 PM] Loading 1 platforms...
Feb 14 14:19:30 homebridge homebridge[479]: [2/14/2018, 2:19:30 PM] [Config] Initializing config platform...
Feb 14 14:19:30 homebridge homebridge[479]: [2/14/2018, 2:19:30 PM] Loading 2 accessories...
Feb 14 14:19:30 homebridge homebridge[479]: [2/14/2018, 2:19:30 PM] [TV Backlight] Initializing Hyperion accessory...
Feb 14 14:19:31 homebridge homebridge[479]: [2/14/2018, 2:19:31 PM] [thermostaat] Initializing NefitEasy accessory...

**Comment by StefanNienhuis** [comment]
Did you install the plugin? I don't see a line that says Loading homebridge-olisto

**Comment by daaf84** [comment]
I did, see my last log. When I delete the Olisto part in the config, Homebridge starts normal.
It looks like it crashes on loading Olisto or the config part of it. I've used a json checker and was good.

**Comment by StefanNienhuis** [comment]
I can't see the error message in your log, could you start homebridge manually and show me the console?

**Comment by StefanNienhuis** [comment]
Sorry for close didn't do that myself

**Comment by daaf84** [comment]
No problem. I will first add olisto to my config again, start it and then copy the log. One moment please .

**Comment by daaf84** [comment]
Can we talk in Dutch here, or can't we?

**Comment by StefanNienhuis** [comment]
Oh, je bent ook Nederlands (:

**Comment by daaf84** [comment]
Ja, maar ik wist niet of het hier per se allemaal in t engels moet ;)

**Comment by StefanNienhuis** [comment]
Ja, maar het kan wel in het nederlands

**Comment by daaf84** [comment]
Ik heb hier vast de config:

{
    "bridge": {
        "name": "Homebridge",
        "homebridgeDirectory":"/var/homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },

    "description": "Configuratie Diefdijk 29",

    "accessories": [
            {
           "accessory": "Hyperion",
           "autoupdate": "true",
           "name": "TV Backlight",
           "ambilightName": "TV Ambilight",
           "host": "192.168.1.10",
           "port": "19444"
            },            

            {
           "accessory" : "NefitEasy",
           "name"      : "thermostaat",
           "options"   :{
                        "serialNumber" : "518913594",
                        "accessKey"    : "9PaSxUCL9bKfpAqE",
                        "password"     : "0000"
                        }
           },
	   {
		"accessory": "mqtt-switch-tasmota",
	
		"name": "SonofY",
	
		"url": "mqtt:192.168.1.3",
		"username": "daaf84",
		"password": "Lavenlaar1",
	
		"topics": {
			"statusGet": "stat/sonoff/RESULT",
			"statusSet": "cmnd/sonoff/POWER",
			"stateGet": "tele/sonoff/STATE"
		},
		"onValue": "ON",
		"offValue": "OFF",
	
		"activityTopic": "tele/sonoff/LWT",
                "activityParameter": "Online",
    
		"startCmd": "cmnd/sonoff/TelePeriod",
		"startParameter": "60",
		
		"manufacturer": "ITEAD",
		"model": "Sonoff",
		"serialNumberMAC": ""
	}
     ],

    "platforms": [
{
      "platform": "config",
      "name": "Config",
      "port": 8080,
      "sudo": false
    },
        {
        "platform": "Olisto",
        "triggs": [
            {
                "name": "KaKu",
                "type": "switch",
                "connecturl": "https://connect.triggi.com/c/BHyR72Y7Rbv4jJyb6Ch7"
            },

	    {
                "name": "KaKu WCD",
                "type": "switch",
                "connecturl": "https://connect.triggi.com/c/Bry93QVdbz58KN2YdMtn"
            }
         ]
         }
    ]
}

**Comment by StefanNienhuis** [comment]
Oke, daar lijkt niks mis mee te zijn

**Comment by daaf84** [comment]
pi@homebridge:~ $ sudo killall homebridge
pi@homebridge:~ $ homebridge
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[2/14/2018, 10:09:54 PM] Loaded plugin: homebridge-config-ui-x
[2/14/2018, 10:09:54 PM] Registering platform 'homebridge-config-ui-x.config'
[2/14/2018, 10:09:54 PM] ---
[2/14/2018, 10:09:55 PM] Loaded plugin: homebridge-hyperion-light
[2/14/2018, 10:09:55 PM] Registering accessory 'homebridge-hyperion.Hyperion'
[2/14/2018, 10:09:55 PM] ---
[2/14/2018, 10:10:02 PM] Loaded plugin: homebridge-nefit-easy
[2/14/2018, 10:10:02 PM] Registering accessory 'homebridge-nefit-easy.NefitEasy'
[2/14/2018, 10:10:02 PM] ---
[2/14/2018, 10:10:06 PM] Loaded plugin: homebridge-olisto
[2/14/2018, 10:10:06 PM] Registering platform 'homebridge-olisto.Olisto'
[2/14/2018, 10:10:06 PM] Registering accessory 'homebridge-olisto.OlistoAccessory'
[2/14/2018, 10:10:06 PM] ---
[2/14/2018, 10:10:06 PM] Loaded config.json with 2 accessories and 0 platforms.
[2/14/2018, 10:10:06 PM] ---
[2/14/2018, 10:10:06 PM] Loading 2 accessories...
[2/14/2018, 10:10:06 PM] [TV Backlight] Initializing Hyperion accessory...
[2/14/2018, 10:10:06 PM] [thermostaat] Initializing NefitEasy accessory...
Setup Payload:
X-HM://0023ISYWYMA88
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
Error: listen EADDRINUSE :::51826
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1277:14)
    at listen (net.js:1313:10)
    at Server.listen (net.js:1409:5)
    at EventedHTTPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:60:19)
    at HAPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:158:20)
    at Bridge.Accessory.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:607:16)
    at Server._publish (/usr/local/lib/node_modules/homebridge/lib/server.js:126:16)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:96:10)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:387:7)
    at startup (bootstrap_node.js:153:9)
    at bootstrap_node.js:500:3
pi@homebridge:~ $

**Comment by daaf84** [comment]
hmm, vanmiddag had ik een andere melding. Ik heb autostart ingesteld via systemd. Weet ff niet hoe ik nu alles stop, opnieuw laadt en handmatig opnieuw start

**Comment by StefanNienhuis** [comment]
De code EADDRINUSE betekent dat homebridge al op die poort draait, dus ik denk dat hij nog in de achtergrond draait.

**Comment by daaf84** [comment]
Ik doe ff een reboot

**Comment by StefanNienhuis** [comment]
Als je het commando "sudo systemctl homebridge stop" doet, moet hij hem stoppen. Daarna kan je homebridge handmatig opstarten

**Comment by daaf84** [comment]
dit was voor het handmatig stoppen:

pi@homebridge:~ $ systemctl status homebridge
● homebridge.service - Node.js HomeKit Server
   Loaded: loaded (/etc/systemd/system/homebridge.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Wed 2018-02-14 22:16:58 CET; 3s ago
  Process: 521 ExecStart=/usr/local/bin/homebridge $HOMEBRIDGE_OPTS (code=exited, status=1/FAILURE)
 Main PID: 521 (code=exited, status=1/FAILURE)

**Comment by daaf84** [comment]
Handmatig gestopt en gestart. 
Nu start ie wel door, maar zegt dat er geen platfoms geladen zijn.

**Comment by StefanNienhuis** [comment]
Hmmm.... staat homebridge-olisto in de config? En staan de accessories wel in homekit?

**Comment by daaf84** [comment]
Ja, config net geopend, en ze staan er in, net als de config-ui-x
De andere accessoires (nefit, hyperion) staan wel in de app en reageren ook gewoon

**Comment by daaf84** [comment]
wil je anders met teamviewer ofzo zelf kijken?

**Comment by StefanNienhuis** [comment]
Nee, ik kan nu even geen teamviewer, kan je de log nu laten zien als je hem handmatig start en de service met systemctl hebt gestopt?

**Comment by daaf84** [comment]
pi@homebridge:~ $ sudo systemctl restart homebridge
pi@homebridge:~ $ sudo systemctl stop homebridge
pi@homebridge:~ $ homebridge
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[2/14/2018, 10:30:09 PM] Loaded plugin: homebridge-config-ui-x
[2/14/2018, 10:30:09 PM] Registering platform 'homebridge-config-ui-x.config'
[2/14/2018, 10:30:09 PM] ---
[2/14/2018, 10:30:10 PM] Loaded plugin: homebridge-hyperion-light
[2/14/2018, 10:30:10 PM] Registering accessory 'homebridge-hyperion.Hyperion'
[2/14/2018, 10:30:10 PM] ---
[2/14/2018, 10:30:17 PM] Loaded plugin: homebridge-nefit-easy
[2/14/2018, 10:30:17 PM] Registering accessory 'homebridge-nefit-easy.NefitEasy'
[2/14/2018, 10:30:17 PM] ---
[2/14/2018, 10:30:21 PM] Loaded plugin: homebridge-olisto
[2/14/2018, 10:30:21 PM] Registering platform 'homebridge-olisto.Olisto'
[2/14/2018, 10:30:21 PM] Registering accessory 'homebridge-olisto.OlistoAccessory'
[2/14/2018, 10:30:21 PM] ---
[2/14/2018, 10:30:21 PM] Loaded config.json with 2 accessories and 0 platforms.
[2/14/2018, 10:30:21 PM] ---
[2/14/2018, 10:30:21 PM] Loading 2 accessories...
[2/14/2018, 10:30:21 PM] [TV Backlight] Initializing Hyperion accessory...
[2/14/2018, 10:30:21 PM] [thermostaat] Initializing NefitEasy accessory...
Setup Payload:
X-HM://0023ISYWYMA88
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
Error: listen EADDRINUSE :::51826
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1277:14)
    at listen (net.js:1313:10)
    at Server.listen (net.js:1409:5)
    at EventedHTTPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:60:19)
    at HAPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:158:20)
    at Bridge.Accessory.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:607:16)
    at Server._publish (/usr/local/lib/node_modules/homebridge/lib/server.js:126:16)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:96:10)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:387:7)
    at startup (bootstrap_node.js:153:9)
    at bootstrap_node.js:500:3
pi@homebridge:~ $

**Comment by StefanNienhuis** [comment]
Hmmmm... raar ik zal hier morgen of overmorgen even naar moeten kijken. Je hoort van me als ik weet wat de oplossing is!

**Comment by daaf84** [comment]
deze werkt niet : 
pi@homebridge:~ $ sudo systemctl homebridge stop
Unknown operation homebridge.

En als ik  ~ $ sudo systemctl stop homebridge  doe, dan krijg ik geen melding, maar wel een nieuwe command line

**Comment by daaf84** [comment]
dank je wel to zo ver. Ik pas weer ff mn config aan nu, dat de rest weer 'normaal' werkt.

**Comment by StefanNienhuis** [comment]
Ik lees op google ook wel: "sudo systemctl stop homebridge.service", als hij hiermee stopt post de log van de handmatige start dan maar. Zo niet, dan kom ik morgen of overmorgen met een oplossing!

**Comment by daaf84** [comment]
Ik heb 2 users, pi en homebridge (die laatste moest ik aanmaken voor systemd volgends deze tutorial:

 Here are the steps that worked for me:
	1	sudo nano /etc/default/homebridge and paste this gist
	2	sudo nano /etc/systemd/system/homebridge.service and paste this gist
	1	I had to remove local from:  ExecStart=/usr/local/bin/homebridge $HOMEBRIDGE_OPTS  because my homebridge installed in /usr/bin/
	3	Create a user to run service: sudo useradd --system homebridge
	4	sudo mkdir /var/homebridge
	5	sudo cp ~/.homebridge/config.json /var/homebridge/
	1	This copies your current user’s config. This assumes you have already added accessories etc.
	6	sudo cp -r ~/.homebridge/persist /var/homebridge
	7	sudo chmod -R 0777 /var/homebridge
	8	sudo systemctl daemon-reload
	9	sudo systemctl enable homebridge
	10	sudo systemctl start homebridge
Type systemctl status homebridge to check the status of the service.


Maar in de pi user map staat ~ /.homebridge en ook een config.json.
De logs die ik eerder stuurde waren gebaseerd op die config en niet die uit ~ /var/homebridge.
Ik denk dat hier zoiezo iets conflicteert.

Maar ik heb nu wel een melding die jou aangaat, nadat ik het dus handmatig gestart heb:

pi@homebridge:~ $ homebridge
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[2/14/2018, 11:09:38 PM] Loaded plugin: homebridge-config-ui-x
[2/14/2018, 11:09:39 PM] Registering platform 'homebridge-config-ui-x.config'
[2/14/2018, 11:09:39 PM] ---
[2/14/2018, 11:09:40 PM] Loaded plugin: homebridge-hyperion-light
[2/14/2018, 11:09:40 PM] Registering accessory 'homebridge-hyperion.Hyperion'
[2/14/2018, 11:09:40 PM] ---
[2/14/2018, 11:09:47 PM] Loaded plugin: homebridge-nefit-easy
[2/14/2018, 11:09:47 PM] Registering accessory 'homebridge-nefit-easy.NefitEasy'
[2/14/2018, 11:09:47 PM] ---
[2/14/2018, 11:09:50 PM] Loaded plugin: homebridge-olisto
[2/14/2018, 11:09:50 PM] Registering platform 'homebridge-olisto.Olisto'
[2/14/2018, 11:09:50 PM] Registering accessory 'homebridge-olisto.OlistoAccessory'
[2/14/2018, 11:09:50 PM] ---
[2/14/2018, 11:09:50 PM] Loaded config.json with 2 accessories and 1 platforms.
[2/14/2018, 11:09:50 PM] ---
[2/14/2018, 11:09:50 PM] Loading 1 platforms...
[2/14/2018, 11:09:50 PM] [Olisto] Initializing Olisto platform...

/usr/local/lib/node_modules/homebridge-olisto/node_modules/olisto/index.js:8
      throw new Error('Invalid connect URL make sure it starts with "https://"!')
            ^
Error: Invalid connect URL make sure it starts with "https://"!
    at new Olisto (/usr/local/lib/node_modules/homebridge-olisto/node_modules/olisto/index.js:8:13)
    at new OlistoAccessory (/usr/local/lib/node_modules/homebridge-olisto/index.js:35:20)
    at OlistoPlatform.accessories (/usr/local/lib/node_modules/homebridge-olisto/index.js:22:27)
    at Server._loadPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:364:20)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:308:16)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:85:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:387:7)
    at startup (bootstrap_node.js:153:9)
    at bootstrap_node.js:500:3
pi@homebridge:~ $

**Comment by StefanNienhuis** [comment]
Voor die error weet ik de oplossing wel: in plaats van connect.triggi.com moet je nu connect.olisto.com gebruiken in de config connect url, het is een beetje onhandig met die naam verandering (:

**Comment by daaf84** [comment]
Ik dacht dat ik dat gisteren al had geprobeerd, maar ik ga het morgen nog een keer proberen. Heb net de terminal afgesloten en ga zelf ook afsluiten. Je hoort het nog van me!

 Dank je wel !!

**Comment by StefanNienhuis** [comment]
Graag gedaan!

**Comment by daaf84** [comment]
Ok, stom genoeg was het probleem toch de url, moest idd olisto zijn ipv triggi. 
Het is alleen wel zo dat als je nu een nieuwe connect aanmaakt, deze nog steeds triggi.com is.
Misschien iets om toch toe te voegen aan de regels?

Toch nog steeds problemen: Homebridge start nu zonder fouten op, ik zie de schakelaars nu ook op de app, alleen geen reactie. Heb ook al een nieuwe trip aangemaakt, zowel een nieuwe connect, als een nieuwe actie in de app van olisto.
De urls werken wel als ik ze in de adresbalk invoer, gevoel door "?value=1" of "?value=0"
De olisto app geeft dan aan dat de trigg 'nu' geactiveerd werd, maar niet als ik het via homekit activeer. Volg je me nog?

Is de homebridge-tiggi Haddon ook nog steeds beschikbaar? Want deze deed het gewoon totdat ik mn hele RBpi opnieuw heb geïnstalleerd.

**Comment by daaf84** [comment]
pi@homebridge:~ $ systemctl status homebridge
● homebridge.service - Node.js HomeKit Server
   Loaded: loaded (/etc/systemd/system/homebridge.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2018-02-15 15:09:10 CET; 16min ago
 Main PID: 688 (homebridge)
   CGroup: /system.slice/homebridge.service
           └─688 homebridge

Feb 15 15:12:43 homebridge homebridge[688]: [2/15/2018, 3:12:43 PM] [thermostaat] Getting current temperature...
Feb 15 15:12:43 homebridge homebridge[688]: [2/15/2018, 3:12:43 PM] [thermostaat] Getting current state..
Feb 15 15:12:43 homebridge homebridge[688]: [2/15/2018, 3:12:43 PM] [thermostaat] Getting target temperature...
Feb 15 15:12:45 homebridge homebridge[688]: [2/15/2018, 3:12:45 PM] [thermostaat] ...current temperature is 18.3
Feb 15 15:12:45 homebridge homebridge[688]: [2/15/2018, 3:12:45 PM] [thermostaat] ...target temperature is 16
Feb 15 15:12:45 homebridge homebridge[688]: [2/15/2018, 3:12:45 PM] [thermostaat] ...current state is off
**Feb 15 15:12:58 homebridge homebridge[688]: Something went wrong with the request.
Feb 15 15:13:05 homebridge homebridge[688]: Something went wrong with the request.
Feb 15 15:13:16 homebridge homebridge[688]: Something went wrong with the request.
Feb 15 15:13:24 homebridge homebridge[688]: Something went wrong with the request.**
pi@homebridge:~ $

**Comment by daaf84** [comment]
En die rij wordt telkens langer als ik een knop van olisto indruk via homekit

**Comment by StefanNienhuis** [comment]
Ik heb de error gevonden! Het probleem is dat 'connect.olisto.com' het niet doet met https van uit NodeJS. Hiervoor moet ik de package updaten. Verwacht vanavond een update op de package!

**Comment by StefanNienhuis** [comment]
De fix staat online! Als je nog problemen hebt, kan je deze issue weer heropenen. Voor nu sluit ik deze issue.

**Comment by daaf84** [comment]
Hij werkt nu helemaal goed!! Dank je wel!
